### ISSUE TITLE
Putting files greater than ~1 GB fails. 

### ISSUE THREAD

**Issue by cottersci** [cottersci/irods_python_client#1]
Putting files greater than ~1 GB fail with the error below. 

Files were sent to dirt.cyverse.org. Files copy fine using iCommands. 

``` bash
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 70, in send
    self.socket.sendall(string)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cotter/GitHub/irods_python_client/src/pyicmd/pyicmd/functional.py", line 21, in put
    dest_obj.write(f.read())
  File "/usr/local/lib/python3.6/dist-packages/irods/data_object.py", line 125, in write
    return self.conn.write_file(self.desc, b.tobytes())
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 470, in write_file
    self.send(message)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 78, in send
    raise NetworkException("Unable to send message")
irods.exception.NetworkException: Unable to send message

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 70, in send
    self.socket.sendall(string)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/irods/data_object.py", line 114, in seek
    return self.conn.seek_file(self.desc, offset, whence)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 487, in seek_file
    self.send(message)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 78, in send
    raise NetworkException("Unable to send message")
irods.exception.NetworkException: Unable to send message

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyicmd", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/cotter/GitHub/irods_python_client/src/pyicmd/bin/pyicmd", line 4, in <module>
    pyicmd.main()
  File "/home/cotter/GitHub/irods_python_client/src/pyicmd/pyicmd/pyicmd.py", line 91, in main
    put(session,unknownargs)
  File "/home/cotter/GitHub/irods_python_client/src/pyicmd/pyicmd/pyicmd.py", line 40, in put
    F.put(session,args.files,args.loc, recursive = args.R)
  File "/home/cotter/GitHub/irods_python_client/src/pyicmd/pyicmd/functional.py", line 21, in put
    dest_obj.write(f.read())
  File "/usr/local/lib/python3.6/dist-packages/irods/data_object.py", line 108, in close
    self.conn.close_file(self.desc, **self.options)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 505, in close_file
    self.send(message)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 78, in send
    raise NetworkException("Unable to send message")
irods.exception.NetworkException: Unable to send message
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
Exception ignored in: <bound method Connection.__del__ of <irods.connection.Connection object at 0x7fbebc677780>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 63, in __del__
    self.disconnect()
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 253, in disconnect
    self.send(disconnect_msg)
  File "/usr/local/lib/python3.6/dist-packages/irods/connection.py", line 78, in send
    raise NetworkException("Unable to send message")
irods.exception.NetworkException: Unable to send message
```

**Comment by cottersci** [comment]
Error also happens using a local Docker based (https://github.com/mjstealey/irods-icommands) irods server
